# Window configuration.
[window]
opacity = 0.90
decorations = "full"

# Window dimensions defined with width and height.
dimensions = { columns = 128, lines = 36 }

# Padding configuration.
padding = { x = 10, y = 10 }

# Scrolling configuration.
[scrolling]
history = 10000
multiplier = 3

# Colors configuration.
[colors]
[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

# Font configuration.
[font]
size = 7.5
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }