# Automatically start tmux when opening Alacritty
[env]
TERM = "alacritty"

# Specify the shell program to launch.
[terminal]
shell = { program = "/usr/bin/tmux", args = ["new-session", "-A", "-s", "default"] }

# Window configuration.
[window]
opacity = 0.90
decorations = "full"

# Window dimensions defined with width and height.
dimensions = { columns = 128, lines = 36 }

# Padding configuration.
padding = { x = 10, y = 10 }

# Scrolling configuration.
[scrolling]
history = 10000
multiplier = 3

# Colors configuration.
[colors]
[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

# Font configuration.
[font]
size = 7.5
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }

# Key bindings configuration.
[keyboard]
  # Copy and Paste like Tilix.
  [[keyboard.bindings]]
  action = "Paste"
  key = "V"
  mods = "Control|Shift"

  [[keyboard.bindings]]
  action = "Copy"
  key = "C"
  mods = "Control|Shift"

  # Open a new Alacritty window (like a new tab).
  [[keyboard.bindings]]
  command = { program = "alacritty", args = [] }
  key = "N"
  mods = "Control|Shift"

  # Toggle fullscreen mode.
  [[keyboard.bindings]]
  action = "ToggleFullscreen"
  key = "F"
  mods = "Control|Shift"

  # Font size controls.
  [[keyboard.bindings]]
  action = "IncreaseFontSize"
  key = "="
  mods = "Control|Shift"

  [[keyboard.bindings]]
  action = "DecreaseFontSize"
  key = "-"
  mods = "Control|Shift"

  [[keyboard.bindings]]
  action = "ResetFontSize"
  key = "0"
  mods = "Control|Shift"

  # Scroll controls.
  [[keyboard.bindings]]
  action = "ScrollPageUp"
  key = "Up"
  mods = "Control|Shift"

  [[keyboard.bindings]]
  action = "ScrollPageDown"
  key = "Down"
  mods = "Control|Shift"

  # Split terminal horizontally (requires tmux).
  [[keyboard.bindings]]
  command = { program = "tmux", args = ["split-window", "-h"] }
  key = "D"
  mods = "Control|Shift"

  # Split terminal vertically (requires tmux).
  [[keyboard.bindings]]
  command = { program = "tmux", args = ["split-window", "-v"] }
  key = "S"
  mods = "Control|Shift"

  # Move between panes (requires tmux).
  [[keyboard.bindings]]
  command = { program = "tmux", args = ["select-pane", "-U"] }
  key = "K"
  mods = "Control|Shift"

  [[keyboard.bindings]]
  command = { program = "tmux", args = ["select-pane", "-D"] }
  key = "J"
  mods = "Control|Shift"

  [[keyboard.bindings]]
  command = { program = "tmux", args = ["select-pane", "-L"] }
  key = "H"
  mods = "Control|Shift"

  [[keyboard.bindings]]
  command = { program = "tmux", args = ["select-pane", "-R"] }
  key = "L"
  mods = "Control|Shift"
